# Site settings
title: Make Zurich Vol. II
email: info@makezurich.ch
description: Make Zurich, Civic Tech and LoRaWAN Hackathon for a better city
baseurl: ''
url: https://makezurich.ch

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: make-zurich
twitter_username: makezurich
facebook_URL:
instagram_username:

# Build settings
markdown: kramdown
